// <auto-generated />
using System;
using GestionProjetSocota.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProjetSocota.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908054427_AjoutValidationPowerUser")]
    partial class AjoutValidationPowerUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionProjetSocota.Models.ActionProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("ProjetId");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.DepartementProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("DepartementsProjets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "CAL"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "IND"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Nom = "LOG"
                        },
                        new
                        {
                            Id = 4,
                            Actif = true,
                            Nom = "IT"
                        },
                        new
                        {
                            Id = 5,
                            Actif = true,
                            Nom = "PRO"
                        },
                        new
                        {
                            Id = 6,
                            Actif = true,
                            Nom = "MPF"
                        },
                        new
                        {
                            Id = 7,
                            Actif = true,
                            Nom = "QUA"
                        },
                        new
                        {
                            Id = 8,
                            Actif = true,
                            Nom = "SUST"
                        },
                        new
                        {
                            Id = 9,
                            Actif = true,
                            Nom = "CTE"
                        },
                        new
                        {
                            Id = 10,
                            Actif = true,
                            Nom = "SALES"
                        },
                        new
                        {
                            Id = 11,
                            Actif = true,
                            Nom = "PLN"
                        });
                });

            modelBuilder.Entity("GestionProjetSocota.Models.HistoriqueProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("HistoriqueProjets");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.JournalErreur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminRequete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateErreur")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodeHttp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Utilisateur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JournauxErreurs");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.PieceJointe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminStockage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("PiecesJointes");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.PlateformeProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("PlateformesProjets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "WEB"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "GPAO"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Nom = "PBI"
                        },
                        new
                        {
                            Id = 4,
                            Actif = true,
                            Nom = "SUN"
                        },
                        new
                        {
                            Id = 5,
                            Actif = true,
                            Nom = "Oracle"
                        },
                        new
                        {
                            Id = 6,
                            Actif = true,
                            Nom = "CRP"
                        },
                        new
                        {
                            Id = 7,
                            Actif = true,
                            Nom = "Mobile"
                        },
                        new
                        {
                            Id = 8,
                            Actif = true,
                            Nom = "SEAM"
                        },
                        new
                        {
                            Id = 9,
                            Actif = true,
                            Nom = "FREvolve"
                        });
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidationPowerUser")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartementProjetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevVolume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerItId")
                        .HasColumnType("int");

                    b.Property<int>("PlateformeProjetId")
                        .HasColumnType("int");

                    b.Property<int>("PourcentageAvancement")
                        .HasColumnType("int");

                    b.Property<int?>("PowerUserId")
                        .HasColumnType("int");

                    b.Property<int>("Priorite")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("StatutPrecedent")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeProjetReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("UniteProjetId")
                        .HasColumnType("int");

                    b.Property<bool>("ValidePowerUser")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DepartementProjetId");

                    b.HasIndex("OwnerItId");

                    b.HasIndex("PlateformeProjetId");

                    b.HasIndex("PowerUserId");

                    b.HasIndex("TypeProjetReferenceId");

                    b.HasIndex("UniteProjetId");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.RFC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstValide")
                        .HasColumnType("bit");

                    b.Property<string>("GainsAttendus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RoiEstime")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("ProjetId");

                    b.HasIndex("SponsorId");

                    b.ToTable("RFCs");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.ReferenceCompteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("DernierNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefixe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniteProjetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniteProjetId")
                        .IsUnique();

                    b.ToTable("ReferenceCompteurs");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.TypeProjetReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("TypesProjets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "InHouse"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "Outsourced"
                        });
                });

            modelBuilder.Entity("GestionProjetSocota.Models.UniteProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prefixe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("UnitesProjets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "CTN",
                            Prefixe = "CF"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "SGL",
                            Prefixe = "SG"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Nom = "CRE",
                            Prefixe = "CR"
                        });
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomADUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.ActionProjet", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projet");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Commentaire", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.HistoriqueProjet", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projet");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Notification", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId");

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.PieceJointe", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.Projet", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.DepartementProjet", "DepartementProjet")
                        .WithMany()
                        .HasForeignKey("DepartementProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "OwnerIt")
                        .WithMany()
                        .HasForeignKey("OwnerItId");

                    b.HasOne("GestionProjetSocota.Models.PlateformeProjet", "PlateformeProjet")
                        .WithMany()
                        .HasForeignKey("PlateformeProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "PowerUser")
                        .WithMany()
                        .HasForeignKey("PowerUserId");

                    b.HasOne("GestionProjetSocota.Models.TypeProjetReference", "TypeProjetReference")
                        .WithMany()
                        .HasForeignKey("TypeProjetReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.UniteProjet", "UniteProjet")
                        .WithMany()
                        .HasForeignKey("UniteProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartementProjet");

                    b.Navigation("OwnerIt");

                    b.Navigation("PlateformeProjet");

                    b.Navigation("PowerUser");

                    b.Navigation("TypeProjetReference");

                    b.Navigation("UniteProjet");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.RFC", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjetSocota.Models.Utilisateur", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("Projet");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("GestionProjetSocota.Models.ReferenceCompteur", b =>
                {
                    b.HasOne("GestionProjetSocota.Models.UniteProjet", "UniteProjet")
                        .WithMany()
                        .HasForeignKey("UniteProjetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UniteProjet");
                });
#pragma warning restore 612, 618
        }
    }
}
